### ISSUE TITLE
Name of `Black.isort.cfg` is `Black.isort`

### ISSUE THREAD

**Issue by spenserblack** [spenserblack/configfiles#4]
Instead of using the builtin tools to split on extensions, it should be assumed that everything before the *first* `.` is the name of the config file.

**Comment by 0xSooki** [comment]
Haii, if I get it correctly Black.isort.cfg should be renamed to Black.isort

**Comment by spenserblack** [comment]
:thinking: I'd like the extension to represent the file type, so maybe `Black.cfg` instead of `Black.isort`.

However, there's a second solution that I was thinking of. `Black.isort.cfg` is currently split into `Black.isort` and `cfg` here:
https://github.com/spenserblack/configfiles/blob/aaeeb624935b8595efede417f806e822941b1d19/scripts/to-json.js#L16-L21
However, being split into `Black` and `isort.cfg` would probably be better, and can be accomplished with `file.split('.')` instead of using `path.parse`.

**Comment by 0xSooki** [comment]
Gotcha, would love to do it

**Comment by spenserblack** [comment]
Thank you!
